### ISSUE TITLE
Unable to load dpp frontend application due to incorrect mime type

### ISSUE THREAD

**Issue by umarfchy** [eclipse-tractusx/digital-product-pass#400]
### Current Behavior
I want to test out the DPP on **minikube**. I created a pv and installed the app application using the command `helm install digital-product-pass tractusx/digital-product-pass`. The applications are running the application and forwarding the port for the DPP frontend, I'm getting the following error in the browser console. 

Error: 

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec

Note that JavaScript is enabled and tested in both normal and incognito mode. 

### Expected Behavior
I was expecting to run the frontend on the forwarded port locally. 

### Steps To Reproduce

System Info:
minikube version: v1.33.1
Ubuntu 22.04.4 LTS Operating System
Chrome & Firefox Browser  

![image](https://github.com/user-attachments/assets/6b55571c-9ee5-4d6d-bbf1-eec8468834fa)

![image](https://github.com/user-attachments/assets/203fabce-fa53-4d40-a797-e5113ee13a4c)

![image](https://github.com/user-attachments/assets/8586a00f-f3b3-4200-a475-513a3e675848)

**Comment by matbmoser** [comment]
Hi @umarfchy,

You need a keycloak instance running to use the front end correctly. 

The realm are in our deployment folder. 

It is also depending on the data space central services to work. Which can be found in the tractus-x umbrella.

**Comment by saudkhan116** [comment]
Hi @umarfchy,

The frontend is protected from authentication mechanism from Keycloak, and the system depends on central services. 

However, you could still run the frontend component (without helm and docker). 

## Steps:
- Run a local keycloak instance in docker, that must have accessibility on a port **8088** in your browser [IAM Keycloak](https://github.com/eclipse-tractusx/digital-product-pass/tree/main/deployment/local/iam)
- Import existing [realm](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/deployment/local/iam/realm.json)
- Change the configuration (clientId, port, url,...) if necessary in [service.const.js](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/dpp-frontend/src/services/service.const.js)
- follow this guide to build and run the frontend : [INSTALL.md -> Installation](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/INSTALL.md#installation)

If you still need any support, please let me know!

**Comment by saudkhan116** [comment]
It seems like an issue with the authentication and backend componet. The backend component cannot work without the dataspace components (shared services) and EDCs.

There is currently no helm chart available for the complete DPP infra setup in this repo, except the umbrella helm chart that  spins up the dataspace shared service for you, and then you can configure DPP and make a connection. 

I know, its a bit complex to understand, but currently is the only way.

Thats actually a good point for us to think about how DPP can be setup as a standalone and run locally via helm deployment.

**Comment by umarfchy** [comment]
Hi @saudkhan116, I took some time to play with the [umbrella project](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main). Using [this tutorial](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/README.md#hosts) I've deployed the stack in minikube with the following helm command 

`helm install   --set centralidp.enabled=true,managed-identity-wallet.enabled=true,dataconsumerOne.enabled=true,tx-data-provider.enabled=true   umbrella tractusx-dev/umbrella   --namespace umbrella   --create-namespace`
  
![image](https://github.com/user-attachments/assets/3fa71f39-c12a-4569-8252-fa917ca23596)

I tried multiple times and it times out every time. However, upon checking the pods, I see all pods are running.

![image](https://github.com/user-attachments/assets/a73cebb3-0af1-4a59-8eea-80dca4572763)

Assuming all pods are deployed, I tried accessing http://centralidp.tx.test/ which gave `404 Not Found`. 
![image](https://github.com/user-attachments/assets/ac213364-a852-422f-8051-4462400a8658)

Assuming there was an issue with my DNS and Ingress, I tried directly forwarding the service and pod (`k port-forward pods/umbrella-centralidp-0 8080:8080`), to see if I could get anything in the browser. However, in both cases, it showed resources not found. 

![image](https://github.com/user-attachments/assets/a79be8f0-38be-4926-8a79-db762d709ef7)

Is there something wrong with my process? I assume this is the first step in preparing the data space. After deploying the dataspace, I need to deploy the edc provider and edc consumer. Once all of these are deployed, I can use the URLs/IPs to connect the dpp backend. Let me know if I'm moving in the right direction. 

I appreciate the help.

**Comment by umarfchy** [comment]
Hi @saudkhan116 , thanks for the response. I installed the helm chart enabling the following parameters:- 
```bash
centralidp.enabled=true
managed-identity-wallet.enabled=true
dataconsumerOne.enabled=true
tx-data-provider.enabled=true
portal.enabled=true
sharedidp.enabled=true
```
```bash
helm install   --set centralidp.enabled=true,managed-identity-wallet.enabled=true,dataconsumerOne.enabled=true,tx-data-provider.enabled=true,portal.enabled=true,sharedidp.enabled=true   umbrella tractusx-dev/umbrella   --namespace umbrella   --create-namespace --debug 
```

The installation was not complete and there were pods created as before. You can also see the debug log here. 

<details> <summary> Click to see the debug logs </summary> <br/>

```bash

install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /home/umar/.cache/helm/repository/umbrella-1.0.0.tgz

coalesce.go:289: warning: destination for umbrella.semantic-hub.hub.ingress.annotations is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for tractusx-connector.vault.injector.webhook.objectSelector is a table. Ignoring non-table value (matchExpressions:
- key: app.kubernetes.io/name
  operator: NotIn
  values:
  - {{ template "vault.name" . }}-agent-injector
)
coalesce.go:289: warning: destination for tractusx-connector.vault.injector.webhook.objectSelector is a table. Ignoring non-table value (matchExpressions:
- key: app.kubernetes.io/name
  operator: NotIn
  values:
  - {{ template "vault.name" . }}-agent-injector
)
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "dataprovider-secret-dtr-postgres-init" Secret
client.go:490: [debug] Ignoring delete failure for "dataprovider-secret-dtr-postgres-init" /v1, Kind=Secret: secrets "dataprovider-secret-dtr-postgres-init" not found
client.go:142: [debug] creating 1 resource(s)
client.go:142: [debug] creating 114 resource(s)
client.go:486: [debug] Starting delete for "umbrella-dataconsumer-1-post-install-vault-setup" Job
client.go:490: [debug] Ignoring delete failure for "umbrella-dataconsumer-1-post-install-vault-setup" batch/v1, Kind=Job: jobs.batch "umbrella-dataconsumer-1-post-install-vault-setup" not found
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job umbrella-dataconsumer-1-post-install-vault-setup with timeout of 5m0s
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: ADDED
client.go:779: [debug] umbrella-dataconsumer-1-post-install-vault-setup: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataconsumer-1-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataconsumer-1-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataconsumer-1-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataconsumer-1-post-install-vault-setup: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataconsumer-1-post-install-vault-setup: MODIFIED
client.go:486: [debug] Starting delete for "umbrella-dataprovider-post-install-vault-setup" Job
client.go:490: [debug] Ignoring delete failure for "umbrella-dataprovider-post-install-vault-setup" batch/v1, Kind=Job: jobs.batch "umbrella-dataprovider-post-install-vault-setup" not found
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job umbrella-dataprovider-post-install-vault-setup with timeout of 5m0s
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: ADDED
client.go:779: [debug] umbrella-dataprovider-post-install-vault-setup: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-vault-setup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-vault-setup: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-vault-setup: MODIFIED
client.go:486: [debug] Starting delete for "umbrella-portal-portal-migrations" Job
client.go:490: [debug] Ignoring delete failure for "umbrella-portal-portal-migrations" batch/v1, Kind=Job: jobs.batch "umbrella-portal-portal-migrations" not found
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job umbrella-portal-portal-migrations with timeout of 5m0s
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: ADDED
client.go:779: [debug] umbrella-portal-portal-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-portal-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-portal-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-portal-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-portal-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-portal-migrations: MODIFIED
client.go:486: [debug] Starting delete for "umbrella-portal-provisioning-migrations" Job
client.go:490: [debug] Ignoring delete failure for "umbrella-portal-provisioning-migrations" batch/v1, Kind=Job: jobs.batch "umbrella-portal-provisioning-migrations" not found
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job umbrella-portal-provisioning-migrations with timeout of 5m0s
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: ADDED
client.go:779: [debug] umbrella-portal-provisioning-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-provisioning-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-provisioning-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-provisioning-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: MODIFIED
client.go:779: [debug] umbrella-portal-provisioning-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-portal-provisioning-migrations: MODIFIED
client.go:486: [debug] Starting delete for "umbrella-dataprovider-post-install-testdata" Job
client.go:490: [debug] Ignoring delete failure for "umbrella-dataprovider-post-install-testdata" batch/v1, Kind=Job: jobs.batch "umbrella-dataprovider-post-install-testdata" not found
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job umbrella-dataprovider-post-install-testdata with timeout of 5m0s
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: ADDED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 2, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 2, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 3, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 3, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for umbrella-dataprovider-post-install-testdata: MODIFIED
client.go:779: [debug] umbrella-dataprovider-post-install-testdata: Jobs active: 0, jobs failed: 4, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: 1 error occurred:
	* timed out waiting for the condition


helm.go:84: [debug] failed post-install: 1 error occurred:
	* timed out waiting for the condition


INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598

```

</details>

<details> <summary> Click to see the list of pods </summary> <br/>

```bash 
❯ k get po
NAME                                                        READY   STATUS      RESTARTS        AGE
edc-dataconsumer-1-vault-0                                  1/1     Running     0               3h21m
edc-dataprovider-vault-0                                    1/1     Running     0               3h21m
umbrella-centralidp-0                                       1/1     Running     0               3h21m
umbrella-centralidp-postgresql-0                            1/1     Running     0               3h21m
umbrella-dataconsumer-1-db-0                                1/1     Running     0               3h21m
umbrella-dataconsumer-1-edc-controlplane-75fcbfdb8f-cd979   1/1     Running     0               3h21m
umbrella-dataconsumer-1-edc-dataplane-56984bdb94-ph6ml      1/1     Running     3 (3h17m ago)   3h21m
umbrella-dataconsumer-1-post-install-vault-setup-4wsgc      0/1     Completed   0               3h21m
umbrella-dataprovider-db-0                                  1/1     Running     0               3h21m
umbrella-dataprovider-dtr-78b8c5bc58-l4l54                  1/1     Running     3 (3h17m ago)   3h21m
umbrella-dataprovider-dtr-db-0                              1/1     Running     0               3h21m
umbrella-dataprovider-edc-controlplane-65d469d944-gk4xh     1/1     Running     0               3h21m
umbrella-dataprovider-edc-dataplane-69444b445b-ck2zx        1/1     Running     2 (3h18m ago)   3h21m
umbrella-dataprovider-post-install-testdata-8xxtb           0/1     Error       0               3h9m
umbrella-dataprovider-post-install-testdata-9m882           0/1     Error       0               3h
umbrella-dataprovider-post-install-testdata-dj86n           0/1     Error       0               3h12m
umbrella-dataprovider-post-install-testdata-ggfwr           0/1     Error       0               3h11m
umbrella-dataprovider-post-install-testdata-h9x9h           0/1     Error       0               3h6m
umbrella-dataprovider-post-install-testdata-qb42s           0/1     Error       0               3h13m
umbrella-dataprovider-post-install-testdata-xz4sm           0/1     Error       0               3h14m
umbrella-dataprovider-post-install-vault-setup-54ltf        0/1     Completed   0               3h17m
umbrella-dataprovider-submodelserver-84bbf578b5-d5lm2       1/1     Running     0               3h21m
umbrella-portal-administration-service-7865b49d96-rv6qd     1/1     Running     0               3h21m
umbrella-portal-assets-6fbcdc5776-pmppv                     1/1     Running     0               3h21m
umbrella-portal-backend-postgresql-0                        1/1     Running     0               3h21m
umbrella-portal-marketplace-app-service-766d675c9c-hp4k4    1/1     Running     0               3h21m
umbrella-portal-notification-service-6f85988f49-vxprr       1/1     Running     0               3h21m
umbrella-portal-portal-77677c489f-bl7vx                     1/1     Running     0               3h21m
umbrella-portal-portal-migrations-fnsn8                     0/1     Completed   0               3h17m
umbrella-portal-processes-worker-28736030-tgbx4             0/1     Completed   0               12m
umbrella-portal-processes-worker-28736035-t7x2x             0/1     Completed   0               7m6s
umbrella-portal-processes-worker-28736040-6njsk             0/1     Completed   0               2m6s
umbrella-portal-provisioning-migrations-zzld6               0/1     Completed   0               3h15m
umbrella-portal-registration-5c844f697-wvs5k                1/1     Running     0               3h21m
umbrella-portal-registration-service-564c55d98f-xlmtt       1/1     Running     0               3h21m
umbrella-portal-services-service-58456df75c-7g892           1/1     Running     0               3h21m
umbrella-sharedidp-0                                        1/1     Running     0               3h21m
umbrella-sharedidp-postgresql-0                             1/1     Running     0               3h21m

```

</details>


I tried forwarding port using `k port-forward pods/umbrella-centralidp-0 8080:8080` however, it showed `Resource not found`. 

Also, I noticed that one of the post install jobs was failing. The log seems to indicate issue with connectivity. 

<details>
<summary>Click to see the logs for failed job</summary><br/>

```bash
k logs jobs.batch/umbrella-dataprovider-post-install-testdata


Found 7 pods, using pod/umbrella-dataprovider-post-install-testdata-xz4sm
Submodel: http://umbrella-dataprovider-submodelserver:8080
Registry: http://umbrella-dataprovider-dtr:8080/api/v3
Controlplane: http://umbrella-dataprovider-edc-controlplane:8084
Dataplane: http://umbrella-dataprovider-edc-dataplane:8081
EDC Key: TEST2
Allowed BPNs: BPNL00000003AYRE
Collecting requests~=2.27.1 (from -r /opt/scripts/requirements.txt (line 1))
  Downloading requests-2.27.1-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting urllib3<1.27,>=1.21.1 (from requests~=2.27.1->-r /opt/scripts/requirements.txt (line 1))
  Downloading urllib3-1.26.19-py2.py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 597.7 kB/s eta 0:00:00
Collecting certifi>=2017.4.17 (from requests~=2.27.1->-r /opt/scripts/requirements.txt (line 1))
  Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer~=2.0.0 (from requests~=2.27.1->-r /opt/scripts/requirements.txt (line 1))
  Downloading charset_normalizer-2.0.12-py3-none-any.whl.metadata (11 kB)
Collecting idna<4,>=2.5 (from requests~=2.27.1->-r /opt/scripts/requirements.txt (line 1))
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.1 MB/s eta 0:00:00
Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.0/163.0 kB 1.3 MB/s eta 0:00:00
Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Downloading idna-3.7-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 1.1 MB/s eta 0:00:00
Downloading urllib3-1.26.19-py2.py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.9/143.9 kB 1.5 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.7.4 charset-normalizer-2.0.12 idna-3.7 requests-2.27.1 urllib3-1.26.19
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Management: http://umbrella-dataprovider-edc-controlplane:8081
Create policy default-policy on EDC http://umbrella-dataprovider-edc-controlplane:8081/management/v2/policydefinitions
<Response [200]>
Traceback (most recent call last):
Successfully created policy default-policy.
  File "/opt/scripts/upload.py", line 417, in <module>
Create policy test on EDC http://umbrella-dataprovider-edc-controlplane:8081/management/v2/policydefinitions
<Response [200]>
Successfully created policy test.
http://umbrella-dataprovider-edc-controlplane:8084
http://umbrella-dataprovider-edc-controlplane:8081
Query Catalog for registry asset http://umbrella-dataprovider-edc-controlplane:8081/management/v2/catalog/request
<Response [500]>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Internal Server Error</title>
</head>
<body><h2>HTTP ERROR 500 Internal Server Error</h2>
<table>
<tr><th>URI:</th><td>/management/v2/catalog/request</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>Internal Server Error</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>

</body>
</html>

    create_registry_asset(edc_upload_urls, edc_bpns, edc_asset_path, edc_contract_definition_path, edc_catalog_path,
  File "/opt/scripts/upload.py", line 252, in create_registry_asset
    print_response(response_)
  File "/opt/scripts/upload.py", line 168, in print_response
    raise Exception("Failed to call service")
Exception: Failed to call service

```
</details>

Also, I created a nginx pod and tried connecting to central idp service from within the pod. However, this also showed resource not found. 

```bash

root@nginx:/# curl 10.244.0.65:8080 
<html><body><h1>Resource not found</h1></body></html>

```
I haven't changed any default values apart from enabling the parameters. Wondering if there are additional changes that are required 😅

**Comment by saudkhan116** [comment]
Hi @umarfchy  from the logs, it seems like a connectivity issue.
Please have a look into the deployment docs here: https://eclipse-tractusx.github.io/docs/tutorials/e2e/connect/deployComponents

**Comment by saudkhan116** [comment]
Since, the required concerns are considered, closing this issue.
